"use client"

import React from 'react'
import { Topbar } from '@/components/layout/Topbar'
import { PageShell } from '@/components/layout/PageShell'
import { useRecommendations } from '@/hooks/useRecommendations'
import { Pill } from '@/components/ui/Pill'
import { Skeleton } from '@/components/ui/Skeleton'
import { EmptyState } from '@/components/ui/EmptyState'
import { Recommendation } from '@/lib/types'
import { api } from '@/lib/api'
import { CheckCircle2, AlertCircle, ArrowRight } from 'lucide-react'
import { cn } from '@/lib/utils'

export default function RecommendationsPage() {
  const brand = "Adore Me" // v1 default
  const { data: recs, isLoading, mutate } = useRecommendations(brand)

  const handleImplement = async (id: number) => {
    try {
      await api.recommendations(brand); // This is just fetch in lib/api, but we need POST implementation. 
      // Let's assume POST works if called directly or update api.ts
      await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080'}/api/recommendations/${id}/implement`, { method: 'POST' });
      mutate();
    } catch (e) {
      console.error(e)
    }
  }

  return (
    <>
      <Topbar title="GEO Recommendations" />
      <PageShell>
        <div className="flex flex-col gap-8">
          <div className="max-w-2xl">
            <h2 className="text-2xl font-black text-slate-900 tracking-tight mb-2">Priority Actions</h2>
            <p className="text-slate-500 leading-relaxed">
              AI Discovery optimization tasks generated by Claude Sonnet based on your latest visibility gaps and competitor citation patterns.
            </p>
          </div>

          {isLoading ? (
            <div className="space-y-4">
              <Skeleton className="h-48 rounded-3xl" />
              <Skeleton className="h-48 rounded-3xl" />
            </div>
          ) : !recs || recs.length === 0 ? (
            <EmptyState 
              message="No pending recommendations. Your current visibility is within stable parameters." 
              title="All Clear"
              icon={<CheckCircle2 size={48} className="text-emerald-500" />}
            />
          ) : (
            <div className="grid grid-cols-1 gap-6">
              {[...recs].sort((a,b) => a.priority - b.priority).map((rec) => (
                <RecommendationCard key={rec.id} recommendation={rec} onImplement={() => handleImplement(rec.id)} />
              ))}
            </div>
          )}
        </div>
      </PageShell>
    </>
  )
}

function RecommendationCard({ 
    recommendation: rec, 
    onImplement 
}: { 
    recommendation: Recommendation,
    onImplement: () => void
}) {
  return (
    <div className="bg-white rounded-3xl border border-slate-200 overflow-hidden shadow-sm flex flex-col md:flex-row transition-all hover:shadow-md">
      <div className={cn(
        "w-full md:w-2 bg-slate-50",
        rec.priority === 1 ? "bg-red-400" : rec.priority === 2 ? "bg-amber-400" : "bg-blue-400"
      )} />
      
      <div className="flex-1 p-8">
        <div className="flex flex-wrap items-center gap-3 mb-6">
           <span className="px-2.5 py-1 bg-slate-900 text-white rounded-lg text-[10px] font-black uppercase tracking-widest">
             Priority {rec.priority}
           </span>
           <Pill variant={rec.category} />
        </div>

        <h3 className="text-xl font-bold text-slate-900 mb-4 leading-snug">
            {rec.action}
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            <div className="space-y-2">
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-1.5">
                    <ArrowRight size={10} className="text-indigo-600" /> Expected Impact
                </p>
                <p className="text-sm text-slate-600 font-medium leading-relaxed">{rec.expected_impact}</p>
            </div>
            <div className="space-y-2">
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-1.5">
                    <AlertCircle size={10} className="text-indigo-600" /> Rationale
                </p>
                <p className="text-sm text-slate-600 leading-relaxed italic">{rec.rationale}</p>
            </div>
        </div>

        <div className="flex items-center justify-between pt-6 border-t border-slate-50">
            <span className="text-xs text-slate-400 font-medium">
                Status: <span className="text-slate-900 font-bold uppercase tracking-widest ml-1">{rec.status}</span>
            </span>
            {rec.status === 'pending' && (
                <button 
                  onClick={onImplement}
                  className="px-6 py-2.5 bg-indigo-600 text-white text-xs font-bold rounded-xl hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-100 uppercase tracking-widest"
                >
                    Mark as Implemented
                </button>
            )}
        </div>
      </div>
    </div>
  )
}
